# This is a basic workflow to help you get started with Actions

name: Debug Build Windows

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: do-something
    
  # Trigger when release created
  release:
    types: # This configuration does not affect the page_build event above
      - created
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Setup NASM
      uses: ilammy/setup-nasm@v1.2.1
      
    - name: Install PIL
      run: pip install Pillow
      
    - uses: suisei-cn/actions-download-file@v1
      id: downloadfile  # Remember to give an ID if you need the output filename
      name: Download USD
      with:
        url: "https://github.com/ux3d/USD/releases/download/v2022.4.2/usd_win_amd64_debug.zip"
        target: ../resources/usd

    - name: Extracting USD
      run: Expand-Archive -Path ../resources/usd/usd_win_amd64_debug.zip -DestinationPath ../resources/usd/

    # Runs a set of commands using the runners shell
    - name: Build UFG
      run:  |
            python ./tools/ufginstall/ufginstall.py --config Debug ../artifacts/ufg ../resources/usd 
    
    - name: Remove build
      uses: JesseTG/rm@v1.0.2
      with:
        path: ../artifacts/ufg/build  

    - name: Remove src
      uses: JesseTG/rm@v1.0.2
      with:
        path: ../artifacts/ufg/src    

    - name: Archive the release
      run: |
            cd ../artifacts
            echo "Create an archive containing the install files"
            Compress-Archive ufg/* ufg_win_amd64_debug.zip
            echo "Done"
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ../artifacts/ufg_win_amd64_debug.zip
        asset_name: ufg_win_amd64_debug.zip
        tag: ${{ github.ref }}
        overwrite: true
